### ISSUE TITLE
Migrate OSC/bc_osc_ansys_workbench to use Dynamic JavaScript.

### ISSUE THREAD

**Issue by ghost** [OSC/bc_osc_ansys_workbench#32]
Migrate to use Dynamic JavaScript.

Child ticket of https://github.com/OSC/ondemand/issues/1657

**Comment by Oglopf** [comment]
This won't work with Ansys out of the box currently. 

Also, there are pieces of the `form.js` that handle license selections which I am unclear what to do with.

**Comment by johrstrom** [comment]
Does some combination of `data-set` and `data-hide` work for the licenses?

**Comment by Oglopf** [comment]
Fixed in PR #33
